name: Deploy Node.js API

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "🔁 Deploying Node API..."
            cd /var/www/html/future-shadi-api
            git pull origin main
            npm install
            pm2 restart future-shadi-api
            echo "✅ API deployed to https://api.futureshadi.com"
